### ISSUE TITLE
Handle errors until server start

### ISSUE THREAD

**Issue by AkakiGurgenidze** [freeuni-digital-technologies/exam-schedules#36]
რაღაც ერორებია, რომლებიც წინასწარ უნდა შევამოწმოთ და თუ ხდება, არც გავუშვათ სერვერი.

**Comment by lnadi17** [comment]
სერვერი ეშვება, მაგრამ თუ რომელიმე ენდფოინთი ერორს ამოაგდებს იჰენდლება. ეს ქცევა ჯობს, რადგან თეორიულად შეიძლება რაღაც ენდფოინთებმა იმუშაონ მაინც და მაგის გამო მთელი სერვერის აპლიკაციის გაჩერება არ ღირს. ტესტები ისე გვიწერია რომ თუ რამე პრობლემაა დაიჭერს და ფროდაქშენზე ეგეთი ბილდი ვერ მოხვდება. მოკლედ ვხურავთ ამ ეტაპზე.
